apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Adjust size as needed
  storageClassName: standard  # Use your cluster's default storage class
